// Generated by build-icons.ts from svg. Do not edit it by hand:
// add or change an .svg file there, then run `bun run icons:build`.

export const ICON_VIEWBOX = '0 0 24 24'

export const icons = {
  add: '<path fill-rule="evenodd" d="M12.006 3.503a1.5 1.5 0 0 1 1.5 1.5v5.503h5.504a1.5 1.5 0 0 1 0 3h-5.504v5.504a1.5 1.5 0 0 1-3 0v-5.504H5.002a1.5 1.5 0 0 1 0-3h5.504V5.002a1.5 1.5 0 0 1 1.5-1.5" clip-rule="evenodd"/>',
  'arrow-right-col': '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 12V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8m0 4h17m-3-3 3 3-3 3"/>',
  calendar: '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.001" d="M4.002 7.004a2 2 0 0 1 2.001-2.001h12.006a2 2 0 0 1 2.001 2V19.01a2 2 0 0 1-2.001 2H6.003a2 2 0 0 1-2.001-2zm12.006-4.002v4.002M8.004 3.002v4.002m-4.002 4.002H20.01m-9.004 4.002h1m0 0v3.001"/>',
  check: '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.25" d="m6 12.64 3.693 4.148L18 7.455"/>',
  'chevron-right': '<g fill="none" fill-rule="evenodd"><path d="M24 0v24H0V0zM12.593 23.258l-.011.002-.071.035-.02.004-.014-.004-.071-.035q-.016-.005-.024.005l-.004.01-.017.428.005.02.01.013.104.074.015.004.012-.004.104-.074.012-.016.004-.017-.017-.427q-.004-.016-.017-.018m.265-.113-.013.002-.185.093-.01.01-.003.011.018.43.005.012.008.007.201.093q.019.005.029-.008l.004-.014-.034-.614q-.005-.019-.02-.022m-.715.002a.02.02 0 0 0-.027.006l-.006.014-.034.614q.001.018.017.024l.015-.002.201-.093.01-.008.004-.011.017-.43-.003-.012-.01-.01z"/><path fill="currentColor" d="M15.707 11.293a1 1 0 0 1 0 1.414l-5.657 5.657a1 1 0 1 1-1.414-1.414l4.95-4.95-4.95-4.95a1 1 0 0 1 1.414-1.414z"/></g>',
  'chevrons-right': '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.001" d="m7.004 17.009 5.002-5.003-5.002-5.003m6.003 10.006 5.002-5.003-5.002-5.003"/>',
  close: '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-width="2.001" d="m5.64 5.64 12.734 12.735m-12.735 0L18.374 5.64"/>',
  cols: '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-width="2.001" d="M12.006 4.002V20.01m-7.003 0H19.01a1 1 0 0 0 1-1V5.003a1 1 0 0 0-1-1.001H5.003a1 1 0 0 0-1.001 1V19.01a1 1 0 0 0 1 1Z"/>',
  copy: '<g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.001"><path d="M7.004 9.672a2.67 2.67 0 0 1 2.668-2.668h8.67a2.67 2.67 0 0 1 2.669 2.668v8.67a2.67 2.67 0 0 1-2.669 2.669h-8.67a2.67 2.67 0 0 1-2.668-2.669z"/><path d="M4.014 16.745a2 2 0 0 1-1.012-1.737V5.003c0-1.101.9-2.001 2-2.001h10.006c.75 0 1.158.385 1.5 1"/></g>',
  csv: '<path d="M12.006 3.002c-4.422 0-8.004 1.79-8.004 4.002s3.582 4.002 8.004 4.002 8.004-1.791 8.004-4.002-3.582-4.002-8.004-4.002M4.002 9.005v3.001c0 2.211 3.582 4.002 8.004 4.002s8.004-1.79 8.004-4.002V9.005c0 2.21-3.582 4.002-8.004 4.002s-8.004-1.791-8.004-4.002m0 5.002v3.002c0 2.21 3.582 4.002 8.004 4.002s8.004-1.791 8.004-4.002v-3.002c0 2.211-3.582 4.002-8.004 4.002s-8.004-1.79-8.004-4.002"/>',
  down: '<path d="M13.645 14.856a2.19 2.19 0 0 1-3.29 0l-4.033-4.401a1.284 1.284 0 0 1 0-1.703 1.035 1.035 0 0 1 1.56 0l4.03 4.403a.114.114 0 0 0 .173 0l4.032-4.402a1.035 1.035 0 0 1 1.559 0 1.284 1.284 0 0 1 0 1.702z"/>',
  download: '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.001" d="M4.002 17.009v2a2 2 0 0 0 2.001 2.002h12.006a2 2 0 0 0 2.001-2.001v-2.001M7.004 11.006l5.002 5.002 5.003-5.002m-5.003-7.004v12.006"/>',
  draggable: '<path d="M10.005 15.008a2.001 2.001 0 1 1 4.002 0 2.001 2.001 0 0 1-4.002 0m6.003 0a2.001 2.001 0 1 1 4.002 0 2.001 2.001 0 0 1-4.002 0m-12.006 0a2.001 2.001 0 1 1 4.002 0 2.001 2.001 0 0 1-4.002 0m6.003-6.003a2.001 2.001 0 1 1 4.002 0 2.001 2.001 0 0 1-4.002 0m6.003 0a2.001 2.001 0 1 1 4.002 0 2.001 2.001 0 0 1-4.002 0m-12.006 0a2.001 2.001 0 1 1 4.002 0 2.001 2.001 0 0 1-4.002 0"/>',
  filter: '<path fill-rule="evenodd" d="M1.5 3h21v2.25h-21zm6 15h9v2.25h-9zm-1.875-7.5H4.5v2.25h15V10.5z" clip-rule="evenodd" shape-rendering="geometricprecision"/>',
  filters: '<path d="M21.01 4.002v2.001h-1l-6.003 9.005v7.003h-4.002v-7.003L4.002 6.003h-1V4.002z"/>',
  grid: '<g fill="none" stroke="currentColor" stroke-linejoin="round" stroke-width="3" transform="scale(.5004)"><rect width="36" height="36" rx="3" transform="translate(6 6)"/><path d="M13 13h8v8h-8zm0 14h8v8h-8z"/><path stroke-linecap="round" d="M27 28h8m-8 7h8m-8-22h8m-8 7h8"/></g>',
  link: '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.751" d="m9.005 15.008 6.003-6.003m-4.002-3.002.463-.536a5.003 5.003 0 0 1 7.074 7.075l-.534.465m-5.002 5.002-.398.534a5.073 5.073 0 0 1-7.13 0 4.97 4.97 0 0 1 0-7.074l.524-.463"/>',
  'no-filter': '<path d="M13.269 10.5h2.25l-4.038-5.25h-2.25z"/><path fill-rule="evenodd" d="M5.625 10.5H4.5v2.25h12.75l-1.731-2.25zM1.5 3h8.25l1.731 2.25H1.5zm21 2.25h-7.2L13.5 3h9zM15 18v2.25H9.231V18z" clip-rule="evenodd"/><path d="M15 12.75h2.25l3.188 4.125-1.5 1.125-2.813-3.75zM9.75 3H7.5L6 1l1.5-1z"/>',
  plus: '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-width="2.25" d="M5.002 12.006H19.01m-7.003 7.003V5.003"/>',
  search: '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-width="2.001" d="m15.886 15.886 4.245 4.245m-2.122-9.625a7.505 7.505 0 1 1-15.007 0 7.505 7.505 0 0 1 15.007 0Z"/>',
  'select-caret': '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.001" d="m7.004 15.008 5.002 5.002 5.003-5.002M7.004 9.005l5.002-5.003 5.003 5.003"/>',
  sheet: '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.501" d="M3.002 5.003a2 2 0 0 1 2-2.001H19.01a2 2 0 0 1 2 2V19.01a2 2 0 0 1-2 2H5.003a2 2 0 0 1-2.001-2zm0 5.002H21.01M10.005 3.001v18.01"/>',
  sheets: '<path d="M19.01 11.006V9.005h-8.004V5.003H9.005v4.002H5.003v2h4.002v8.005h2v-8.004zm0-8.004c.5 0 1 .2 1.39.61.41.39.61.89.61 1.39V19.01c0 .5-.2 1-.61 1.39-.39.41-.89.61-1.39.61H5.003c-.5 0-1.001-.2-1.391-.61-.41-.39-.61-.89-.61-1.39V5.003c0-.5.2-1.001.61-1.391.39-.41.89-.61 1.39-.61z"/>',
  slash: '<path d="M19.01 3.002H5.003c-1.101 0-2.001.9-2.001 2V19.01c0 1.1.9 2 2 2H19.01c1.1 0 2-.9 2-2V5.003c0-1.101-.9-2.001-2-2.001M9.305 19.01H7.004l7.703-14.007h2.302z"/>',
  'sort-ascending': '<path d="M11.298 7.296a1.005 1.005 0 0 1 1.32-.083l.096.083 6.003 6.003.083.095.053.076.054.097.017.036.027.066.033.108.009.055.01.06.005.057.002.058-.002.06-.006.057-.009.06-.009.053-.033.108-.027.066-.069.133-.066.09-.072.081-.094.083-.077.054-.097.054-.037.016-.066.027-.108.033-.054.009-.06.01-.056.005-.059.002H6.003a1.002 1.002 0 0 1-.783-1.625l.075-.084z"/>',
  'sort-caret': '<path d="M11.298 3.294a1 1 0 0 1 1.416 0l6.003 6.003.072.083.006.007.015.023.044.06.009.015.007.009.013.027.025.045.007.015.009.02.012.034.015.033.008.025.007.02.006.027.012.036.003.028.006.026.003.025.006.033.003.03.003.028v.026l.002.033-.002.033v.025l-.003.027-.003.032-.004.03-.005.03-.006.022-.003.03-.012.036-.006.027-.007.018-.008.027-.015.033-.012.033-.009.018-.007.018-.024.045-.015.027-.006.01-.01.014-.042.06-.012.018-.004.003-.006.011a1 1 0 0 1-.155.153l-.009.006-.022.015-.057.043-.016.01-.01.007-.028.013-.044.024-.018.008-.018.009-.033.012-.033.015-.024.006-.02.009-.028.006-.036.012-.03.003-.024.006-.027.003-.031.006-.032.003-.027.003h-.025l-.033.001H6.003a1 1 0 0 1-.708-1.708zm6.711 9.712.033.002h.026l.027.003.031.003.03.006.03.003.023.006.03.003.036.012.027.006.018.008.027.007.033.015.033.012.018.009.018.008.045.024.027.015.009.006.015.009.052.037.026.017.003.004.01.006a1 1 0 0 1 .153.155l.006.009.015.019.044.06.009.017.007.009.014.028.024.044.004.012.012.024.012.033.015.033.008.027.007.019.006.026.012.036.003.03.006.024.003.027.006.031.003.032.003.026v.026l.002.033-.002.033v.025l-.003.027-.003.032-.006.03-.003.03-.006.022-.003.03-.012.036-.006.027-.007.018-.008.027-.015.033-.012.033-.009.018-.007.018-.024.045-.015.027-.006.01-.01.014-.041.06-.012.018-.005.003-.006.011-.072.081-6.003 6.003a1 1 0 0 1-1.416 0l-6.003-6.003a1 1 0 0 1 .708-1.708z"/>',
  'sort-descending': '<path d="M18.009 9.005c.852 0 1.297.986.783 1.624l-.075.084-6.003 6.003a1.005 1.005 0 0 1-1.32.083l-.096-.083-6.003-6.003-.082-.094-.054-.077-.054-.097-.017-.036-.027-.066-.033-.108-.009-.054-.01-.06-.005-.058v-.117l.006-.058.009-.06.009-.053.033-.108.027-.066.069-.133.066-.09.072-.081.095-.083.076-.054.098-.054.036-.016.066-.027.107-.033.054-.009.06-.01.057-.005z"/>',
  'spinner-ring': '<g fill="currentColor"><path fill="currentColor" d="M12,1A11,11,0,1,0,23,12,11,11,0,0,0,12,1Zm0,19a8,8,0,1,1,8-8A8,8,0,0,1,12,20Z" opacity=".25"/><path fill="currentColor" d="M10.14,1.16a11,11,0,0,0-9,8.92A1.59,1.59,0,0,0,2.46,12,1.52,1.52,0,0,0,4.11,10.7a8,8,0,0,1,6.66-6.61A1.42,1.42,0,0,0,12,2.69h0A1.57,1.57,0,0,0,10.14,1.16Z"><animateTransform attributeName="transform" dur="0.75s" repeatCount="indefinite" type="rotate" values="0 12 12;360 12 12"/></path></g>',
  table: '<path d="M5 4h14a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2m0 4v4h6V8zm8 0v4h6V8zm-8 6v4h6v-4zm8 0v4h6v-4z"/>',
  xlsx: '<path d="M21.18 3.252q.33 0 .59.25.241.24.241.58V19.93q0 .34-.24.58-.26.25-.59.25H7.834q-.33 0-.59-.25-.24-.24-.24-.58v-2.921H2.83q-.33 0-.59-.24-.24-.26-.24-.59V7.833q0-.33.24-.59.26-.24.59-.24h4.173V4.082q0-.34.24-.58.26-.25.59-.25m-.83 9.815 1.18 2.22h1.791l-1.971-3.221 1.931-3.172h-1.71l-1.091 2.011-.04.06-.03.07q-.26-.53-.56-1.07-.25-.53-.531-1.07h-1.81l1.89 3.191-2.051 3.202h1.78m8.105 4.222v-2.501H8.254v2.5m5.633-3.751v-3.122h-1.881v3.122m1.88-4.372V8.254h-1.88v3.132m1.88-4.382V4.502H8.255v2.502M20.76 19.51v-2.501h-5.622v2.5m5.622-3.751v-3.122h-5.622v3.122m5.622-4.372V8.254h-5.622v3.132m5.622-4.382V4.502h-5.622v2.502Z"/>',
}

export type IconName = keyof typeof icons

/** Scope SVG definitions and their references to one framework useId() value. */
export function iconMarkup(name: IconName, instanceId: string): string {
  const body = icons[name]
  const ids = new Map([...body.matchAll(/\sid="([^"]+)"/g)].map(([, id]) => [id, `icon-${Array.from(instanceId, c => c.codePointAt(0)!.toString(16)).join('-')}-${id}`]))
  if (!ids.size) return body
  const scoped = (id: string) => ids.get(id) ?? id
  let markup = body.replace(/ (id|href|xlink:href|aria-labelledby|aria-describedby|begin|end)="([^"]*)"/g, (attribute, key: string, value: string) => {
    if (key === 'id') return ` id="${scoped(value)}"`
    if (key === 'href' || key === 'xlink:href') return ` ${key}="${value.startsWith('#') ? '#' + scoped(value.slice(1)) : value}"`
    if (key.startsWith('aria-')) return ` ${key}="${value.split(/\s+/).map(scoped).join(' ')}"`
    return ` ${key}="${value.split(';').map(part => {
      const leading = part.match(/^\s*/)?.[0] ?? ''
      const timing = part.trimStart()
      // Longest first: IDs may contain dots, as may animation event names.
      const id = [...ids.keys()].sort((a, b) => b.length - a.length).find(id => timing.startsWith(id + '.'))
      return id ? leading + scoped(id) + timing.slice(id.length) : part
    }).join(';')}"`
  })
  markup = markup.replace(/url\(\s*(['"]?)#([^\s)'"]+)\1\s*\)/g, (_, quote: string, id: string) => `url(${quote}#${scoped(id)}${quote})`)
  // SVGO prefixes stylesheet selectors at build time; scope them at render time too.
  return markup.replace(/<style([^>]*)>([\s\S]*?)<\/style>/g, (_, attributes: string, css: string) =>
    `<style${attributes}>${css.replace(/#((?:\\.|[a-zA-Z0-9_-])+)/g, (match, selector: string) => {
      const id = selector.replace(/\\(.)/g, '$1')
      return ids.has(id) ? '#' + scoped(id).replace(/[^a-zA-Z0-9_-]/g, '\\$&') : match
    })}</style>`)
}
